datasets:
  egfr_v3:
    data_to_load:
      file_path: "data/EGFR/DCI/egfr_v3/egfr_v3-averaged-dci.csv"
      condition: "egfr_v3"
      swap: false
      start: 268
      myformat: false
      shift_dci: true
    output: 'output/EGFR/egfr_v3'
    title: 'EGFR v3'
    color: '#1f77b4'

  egfr_v3_var:
    data_to_load:
      file_path: "data/EGFR/DCI/egfr_v3/egfr-v3-variance-dci.csv"
      condition: "egfr_v3 variance"
      swap: false
      start: 268
      myformat: false
      shift_dci: true
    output: 'output/EGFR/egfr_v3'
    title: 'EGFR v3 variance'
    color: '#1f77b4'

  WT:
    data_to_load:
      file_path: "data/EGFR/DCI/WT_v3_range/egfr-averaged-dci.csv"
      condition: "WT"
      swap: false
      start: 1
      myformat: false
    output: 'output/EGFR/egfr_v3'
    title: 'EGFR WT'
    color: '#1f77b4'
all:
  all_output: 'output/EGFR/egfr_v3/heatmaps'
  all_title: 'EGFR_v3 DCI'
  heatmap_dir: output/EGFR/egfr_v3/heatmaps